version: 1.2.{build}

skip_tags: true
skip_commits:
  files:
    - "**/*.md"
  message: /updated readme.*|update readme.*s|update docs.*|update version.*/

image: Previous Visual Studio 2013
# allow WMF 5 functionality (e.g. POSHgallery)
os: WMF 5
install:
  - ps: . .\build.ps1 -Bootstrap
  - ps: git config --local user.email 13959569+blindzero@users.noreply.github.com
  - ps: git config --local user.name Matthias Fleschuetz

environment:
  NUGET_API_KEY:
    secure: uFGiUc2uJ1sN33NC4OYLR/ZgVbA5QELkVNi7yC4Nt9HBQKyqx65T2rn+KTrvhUq6
  GITHUB_API_KEY:
    secure: 8p/Cqvhu4dXtC341VlxuV958IhvG1RQlJgX299CQwJw/fzIC5f6lVADq3hZrgwSY

build_script:
  - ps: . .\build.ps1 Build

test_script:
  - ps: . .\build.ps1 TestIntegration

#deploy_script:
#- ps: |
#  if ($deploy) {
#    . .\build.ps1 Publish
#    git config --global credential.helper store
#    Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GITHUB_API_KEY):x-oauth-basic@github.com`n"
#    $gitOut = git push 2>&1
#    if ($?) {$out} else {$out.Exception}
#      
#  }