version: 1.3.{build}

skip_tags: true
skip_commits:
  files:
    - "**/*.md"
  message: /updated readme.*|update readme.*s|update docs.*|update version.*|readme*/

image: Previous Visual Studio 2013
# allow WMF 5 functionality (e.g. POSHgallery)
os: WMF 5
install:
  # installing necessary tools by PSDepend bootstrap (dependencies.psd1)
  - ps: . .\build.ps1 -Bootstrap
  # do some basic git configurations for later commits
  - ps: git config --local user.email 13959569+blindzero@users.noreply.github.com
  - ps: git config --local user.name Matthias Fleschuetz

environment:
  # NUGET API KEY FOR PUBLISHING
  NUGET_API_KEY:
    secure: uFGiUc2uJ1sN33NC4OYLR/ZgVbA5QELkVNi7yC4Nt9HBQKyqx65T2rn+KTrvhUq6
  # GITHUB API KEY FOR RELEASE MANAGEMENT AND REPO ACCESS
  GITHUB_API_KEY:
    secure: 8p/Cqvhu4dXtC341VlxuV958IhvG1RQlJgX299CQwJw/fzIC5f6lVADq3hZrgwSY

build_script:
  - ps: . .\build.ps1 Build

test_script:
  # run tests
  - ps: |
      try {
        . .\build.ps1 TestIntegration
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $env:BHBuildOutput\testResults.xml))
        Add-AppVeyorMessage -Message "Tests Sucessfull" -Category Information
      }
      catch {
        Add-AppVeyorMessage -Message "Tests Failed!" -Category Error -Details "$($_.Exception.Message)"
        throw
      }

#deploy_script:
#- ps: |
#  if ($deploy) {
#    . .\build.ps1 Publish
#    git config --global credential.helper store
#    Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GITHUB_API_KEY):x-oauth-basic@github.com`n"
#    git commit -m " v$env:APPVEYOR_BUILD_VERSION"
#    git push      
#  }